apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pinchflat.fullname" . }}
  labels:
    {{- include "pinchflat.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }} 
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClass }}