apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinchflat.fullname" . }}
  labels:
    {{- include "pinchflat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  publishNotReadyAddresses: {{ .Values.publishNotReadyAddresses | default false }}
  selector:
    {{- include "pinchflat.selectorLabels" . | nindent 4 }}
